version: '3.8'

volumes:
  postgres_data:
    driver: local

networks:
  hotel-booking-service-network:
    driver: bridge

services:
  hotel_booking_backend:
    image: hotel_booking_backend_image
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/springboot-docker-compose-app
    ports:
      - "8080:8080"
    depends_on:
      keycloak:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/booking_service_db
      SPRING_DATASOURCE_USERNAME: christos
      SPRING_DATASOURCE_PASSWORD: user91234
      KEYCLOAK_URL: http://keycloak:8080/auth
    networks:
      - hotel-booking-service-network

  postgres:
    image: postgres:14.1
    volumes:
      - type: bind
        source: ./docker/postgres/init-sql
        target: /docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: booking_service_db
      POSTGRES_USER: christos
      POSTGRES_PASSWORD: user91234
      KEYCLOAK_HOST: keycloak
      KEYCLOAK_PORT: 8000
    ports:
      - "5432:5432"
    networks:
      - hotel-booking-service-network
  keycloak:
      depends_on:
        - postgres
      image: quay.io/keycloak/keycloak:21.1.0
      ports:
        - '8000:8080'
      volumes:
        - ./docker/keycloak/realm.json:/opt/keycloak/data/import/realm.json
      command:
        - start-dev
        - --import-realm
      environment:
        DB_VENDOR: postgres
        DB_ADDR: postgres
        DB_PORT: 5432
        DB_DATABASE: booking_service_db
        DB_SCHEMA: keycloak
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      networks:
        - hotel-booking-service-network