spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:christos}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/booking_service_db}
    password: ${SPRING_DATASOURCE_PASSWORD:user91234}
    database-platform: postgres
    show-sql: true
my_keycloak:
  client_secret: YSwfd956q5TKze8aCsCiR23joPxU1TIo
  grant_type: client_credentials
  realm: hotel_booking_service
  client_id: hotel_booking_backend
keycloak:
  use-resource-role-mappings: false
  realm: hotel_booking_service
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8000/auth}
  resource: spring-app
  bearer-only: true
  public-client: true